### PR TITLE
Git week1

### PR DESCRIPTION
**Pull request by slastushevskyi**
Exercise 2

### CODE REVIEW

**Review by lupescuas — APPROVED** [review]
I think this recipe  is missing am example :))
MMmhhmmmm <3

**Comment by slastushevskyi** [comment]
My wife just made borshch yesterday while I was studying in HYF. So I can
attached the picture, but problem is that there is not much left🤪

man. 14. nov. 2022 kl. 13.38 skrev Adrian Lupescu ***@***.***

**Comment by lupescuas** [comment]
@slastushevskyi ... ok :D

**Pull request merged**
